language: python

python:
    - 3.6.5

install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install coveralls

scripts:
    - pytest --cov=app/

after_success:
    - coveralls